CREATE TABLE comments (id INT AUTO_INCREMENT NOT NULL, task_id INT NOT NULL, comment VARCHAR(2000) NOT NULL, creation_date DATETIME NOT NULL, INDEX IDX_5F9E962A8DB60186 (task_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
ALTER TABLE comments ADD CONSTRAINT FK_5F9E962A8DB60186 FOREIGN KEY (task_id) REFERENCES tasks (id);
ALTER TABLE tasks CHANGE due_date due_date DATETIME NOT NULL, CHANGE creation_date creation_date DATETIME NOT NULL;
