<?php

namespace TaskManagerBundle\Repository;

/**
 * TaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAll()
    {
        return $this->findBy(array(), array('dueDate' => 'ASC'));
    }

    public function getAllNotClosedTasks()
    {
        $query = $this->createQueryBuilder('t')
            ->where("t.status != 'Closed'")
            ->orderBy('t.dueDate', 'ASC')
            ->getQuery();
        return $query->getResult();
    }

}
